services:
  - type: web
    name: property-log
    env: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x setup_binaries.sh
      ./setup_binaries.sh
    startCommand: |
      source $HOME/.profile
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CLAUDE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: property-log-db
          property: connectionString
      - key: PATH
        value: /opt/render/project/src/bin:$PATH
      - key: LD_LIBRARY_PATH
        value: /opt/render/project/src/lib:$LD_LIBRARY_PATH
      - key: TESSDATA_PREFIX
        value: /opt/render/project/src/share/tessdata

databases:
  - name: property-log-db
    databaseName: property_log
    user: property_log_user
    plan: starter
