services:
  - type: web
    name: property-log
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        pkg-config \
        poppler-utils \
        tesseract-ocr \
        tesseract-ocr-eng
      pip install -r requirements.txt
      chmod +x setup_binaries.sh
      ./setup_binaries.sh
      # Create directory for Google Cloud credentials
      mkdir -p /opt/render/project/src/.google
      echo "$GOOGLE_CLOUD_CREDENTIALS" > /opt/render/project/src/.google/credentials.json
    startCommand: |
      source $HOME/.profile
      export GOOGLE_APPLICATION_CREDENTIALS="/opt/render/project/src/.google/credentials.json"
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CLAUDE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: property-log-db
          property: connectionString
      - key: PATH
        value: /usr/bin:/usr/local/bin:/opt/render/project/src/bin:$PATH
      - key: LD_LIBRARY_PATH
        value: /opt/render/project/src/lib:$LD_LIBRARY_PATH
      - key: TESSDATA_PREFIX
        value: /opt/render/project/src/share/tessdata
      - key: GOOGLE_CLOUD_CREDENTIALS
        sync: false
      - key: LIBREOFFICE_PATH
        value: /usr/bin/soffice
  databases:
  - name: property-log-db
    databaseName: property_log
    user: property_log_user
    plan: starter
