services:
  - type: web
    name: property-log
    env: python
    buildCommand: |
      # Make install script executable
      chmod +x install_packages.sh
      # Run with sudo to ensure proper permissions
      sudo ./install_packages.sh || ./install_packages.sh
      pip install -r requirements.txt
    startCommand: |
      # Ensure PATH and environment variables are set
      export PATH="/usr/local/bin:$PATH"
      export TESSDATA_PREFIX="/usr/local/share/tessdata"
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: CLAUDE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: property-log-db
          property: connectionString
      - key: PATH
        value: /usr/local/bin:/usr/bin:/bin:$PATH
      - key: TESSDATA_PREFIX
        value: /usr/local/share/tessdata
    buildFilter:
      paths:
        - install_packages.sh
        - requirements.txt
        - app.py
    buildTTL: 30m

databases:
  - name: property-log-db
    databaseName: property_log
    user: property_log
    plan: free
