services:
  - type: web
    name: property-log
    env: python
    buildCommand: |
      # Make install script executable
      chmod +x install_packages.sh
      # Run with sudo to ensure proper permissions
      sudo ./install_packages.sh || ./install_packages.sh
      pip install -r requirements.txt
    startCommand: |
      # Ensure PATH includes system binaries
      export PATH="/usr/local/bin:$PATH"
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: CLAUDE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: property-log-db
          property: connectionString
      - key: PATH
        value: /usr/local/bin:/usr/bin:/bin:$PATH

databases:
  - name: property-log-db
    databaseName: property_log
    user: property_log
    plan: free
